
insert into forma_pagamentos (id, descricao) values (1, 'Cartão de crédito');
insert into forma_pagamentos (id, descricao) values (2, 'Cartão de débito');
insert into forma_pagamentos (id, descricao) values (3, 'Dinheiro');
insert into permissoes (id, nome, descricao) values (1, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into permissoes (id, nome, descricao) values (2, 'EDITAR_COZINHAS', 'Permite editar cozinhas');

INSERT INTO estados (id, nome, uf) VALUES (1, 'Acre', 'AC');
INSERT INTO estados (id, nome, uf) VALUES (2, 'Alagoas', 'AL');
INSERT INTO estados (id, nome, uf) VALUES (3, 'Amazonas', 'AM');
INSERT INTO estados (id, nome, uf) VALUES (4, 'Amapá', 'AP');
INSERT INTO estados (id, nome, uf) VALUES (5, 'Bahia', 'BA');
INSERT INTO estados (id, nome, uf) VALUES (6, 'Ceará', 'CE');
INSERT INTO estados (id, nome, uf) VALUES (7, 'Distrito Federal', 'DF');
INSERT INTO estados (id, nome, uf) VALUES (8, 'Espírito Santo', 'ES');
INSERT INTO estados (id, nome, uf) VALUES (9, 'Goiás', 'GO');
INSERT INTO estados (id, nome, uf) VALUES (10, 'Maranhão', 'MA');
INSERT INTO estados (id, nome, uf) VALUES (11, 'Minas Gerais', 'MG');
INSERT INTO estados (id, nome, uf) VALUES (12, 'Mato Grosso do Sul', 'MS');
INSERT INTO estados (id, nome, uf) VALUES (13, 'Mato Grosso', 'MT');
INSERT INTO estados (id, nome, uf) VALUES (14, 'Pará', 'PA');
INSERT INTO estados (id, nome, uf) VALUES (15, 'Paraíba', 'PB');
INSERT INTO estados (id, nome, uf) VALUES (16, 'Pernambuco', 'PE');
INSERT INTO estados (id, nome, uf) VALUES (17, 'Piauí', 'PI');
INSERT INTO estados (id, nome, uf) VALUES (18, 'Paraná', 'PR');
INSERT INTO estados (id, nome, uf) VALUES (19, 'Rio de Janeiro', 'RJ');
INSERT INTO estados (id, nome, uf) VALUES (20, 'Rio Grande do Norte', 'RN');
INSERT INTO estados (id, nome, uf) VALUES (21, 'Rondônia', 'RO');
INSERT INTO estados (id, nome, uf) VALUES (22, 'Roraima', 'RR');
INSERT INTO estados (id, nome, uf) VALUES (23, 'Rio Grande do Sul', 'RS');
INSERT INTO estados (id, nome, uf) VALUES (24, 'Santa Catarina', 'SC');
INSERT INTO estados (id, nome, uf) VALUES (25, 'Sergipe', 'SE');
INSERT INTO estados (id, nome, uf) VALUES (26, 'São Paulo', 'SP');
INSERT INTO estados (id, nome, uf) VALUES (27, 'Tocantins', 'TO');

INSERT INTO cidades (id, nome, estado_id) VALUES (1, 'Afonso Cláudio', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (2, 'Água Doce do Norte', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (3, 'Águia Branca', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (4, 'Alegre', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (5, 'Alfredo Chaves', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (6, 'Alto Rio Novo', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (7, 'Anchieta', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (8, 'Apiacá', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (9, 'Aracruz', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (10, 'Atilio Vivacqua', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (11, 'Baixo Guandu', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (12, 'Barra de São Francisco', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (13, 'Boa Esperança', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (14, 'Bom Jesus do Norte', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (15, 'Brejetuba', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (16, 'Cachoeiro de Itapemirim', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (17, 'Cariacica', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (18, 'Castelo', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (19, 'Colatina', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (20, 'Conceição da Barra', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (21, 'Conceição do Castelo', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (22, 'Divino de São Lourenço', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (23, 'Domingos Martins', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (24, 'Dores do Rio Preto', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (25, 'Ecoporanga', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (26, 'Fundão', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (27, 'Governador Lindenberg', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (28, 'Guaçuí', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (29, 'Guarapari', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (30, 'Ibatiba', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (31, 'Ibiraçu', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (32, 'Ibitirama', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (33, 'Iconha', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (34, 'Irupi', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (35, 'Itaguaçu', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (36, 'Itapemirim', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (37, 'Itarana', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (38, 'Iúna', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (39, 'Jaguaré', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (40, 'Jerônimo Monteiro', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (41, 'João Neiva', 8);
INSERT INTO cidades (id, nome, estado_id) VALUES (42, 'Laranja da Terra', 8);